apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels: 
    test: app
    kubernetes.io/my-app: first-pod
  annotations:
    description: "this is my first pod in k8s cluster" 
#  namespace: kube-system 
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

