apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myhelmchart.fullname" . }}
  labels:
    {{- include "myhelmchart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "myhelmchart.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "myhelmchart.labels" . | nindent 8 }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
