apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
    - name: ubuntu 
      image: ubuntu
      command: ['sh', '-c', 'sleep 1d']
      env:
        - name: JSON_CONFIG
          valueFrom:
            configMapKeyRef:
              name: my-configmap
              key: config.json
      envFrom:
        - configMapRef:
            name: fromenvfile
