apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  key1: value1
  branchName: develop
  version: "3.4"
  anotherKey: |
    this is a configmap
    multiline value for
    key anotherkey
    and this is the last
    line in this value

  config.json: |
    {"attr1": "value1",
    "attr2": "value2" }
