apiVersion: v1
kind: Pod
metadata:
  name: secure-nginx
spec:
  securityContext:
    runAsNonRoot: true
  containers:
  - image: nginxinc/nginx-unprivileged:1.27
    name: nginx
    securityContext:
      allowPrivilegeEscalation: false
