apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
  labels:
    app: volume-app
spec:
  containers:
  - image: nginx
    name: web
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: vol1
  volumes:
  - name: vol1
    nfs:
      server: harbor.lab.local
      path: /var/nfs-share
