apiVersion: v1
kind: Pod
metadata:
  name: volume-configmap-pod
spec:
  volumes:
    - name: configmap-vol
      configMap:
        name: my-configmap
  containers:
    - name: ubuntu 
      image: ubuntu
      command: ['sh', '-c', 'sleep 1d']
      volumeMounts:
        - name: configmap-vol 
          mountPath: /config
